name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: build binary
        run: go build .
      - name: create tar.gz
        run: tar -czvf languages ./tasu
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tasu
          path: tasu.tar.gz

